package com.dogactanriverdi.movieapp.domain.model.movie.detail

data class MovieDetail(
    val adult: Boolean,
    val backdropPath: String,
    val belongsToCollection: MovieDetailBelongsToCollection,
    val budget: Int,
    val genres: List<MovieDetailGenre>,
    val homepage: String,
    val id: Int,
    val imdbId: String,
    val originCountry: List<String>,
    val originalLanguage: String,
    val originalTitle: String,
    val overview: String,
    val popularity: Double,
    val posterPath: String,
    val productionCompanies: List<MovieDetailProductionCompany>,
    val productionCountries: List<MovieDetailProductionCountry>,
    val releaseDate: String,
    val revenue: Int,
    val runtime: Int,
    val spokenLanguages: List<MovieDetailSpokenLanguage>,
    val status: String,
    val tagline: String,
    val title: String,
    val video: Boolean,
    val voteAverage: Double,
    val voteCount: Int,
)