package com.dogactanriverdi.movieapp.domain.model.tvseries.detail

data class TvSeriesDetail(
    val adult: Boolean,
    val backdropPath: String,
    val createdBy: List<TvSeriesDetailCreatedBy>,
    val episodeRunTime: List<Int>,
    val firstAirDate: String,
    val genres: List<TvSeriesDetailGenre>,
    val homepage: String,
    val id: Int,
    val inProduction: Boolean,
    val languages: List<String>,
    val lastAirDate: String,
    val lastEpisodeToAir: TvSeriesDetailLastEpisodeToAir,
    val name: String,
    val networks: List<TvSeriesDetailNetwork>,
    val nextEpisodeToAir: TvSeriesDetailNextEpisodeToAir,
    val numberOfEpisodes: Int,
    val numberOfSeasons: Int,
    val originCountry: List<String>,
    val originalLanguage: String,
    val originalName: String,
    val overview: String,
    val popularity: Double,
    val posterPath: String,
    val productionCompanies: List<TvSeriesDetailProductionCompany>,
    val productionCountries: List<TvSeriesDetailProductionCountry>,
    val seasons: List<TvSeriesDetailSeason>,
    val spokenLanguages: List<TvSeriesDetailSpokenLanguage>,
    val status: String,
    val tagline: String,
    val type: String,
    val voteAverage: Double,
    val voteCount: Int
)